import { useState, useCallback } from "react";
import { collection, addDoc, updateDoc, getDocs, query, where, orderBy } from "firebase/firestore";
import { db, handleFirestoreError, OperationType } from "../lib/firebase";
import { MarketplaceLead } from "../types";

/**
 * Calculates B2B commission payload based on partner vertical and volume criteria.
 */
export function calculateB2BCommission(
  partnerType: MarketplaceLead["partnerType"],
  payloadDetails?: Record<string, any>
): number {
  switch (partnerType) {
    case "packers_movers":
      // If estimated moving pricing is available, charge 5% commission. Else, charge flat rate of ₹500.
      if (payloadDetails?.estimatedMoveCost && typeof payloadDetails.estimatedMoveCost === "number") {
        return Math.round(payloadDetails.estimatedMoveCost * 0.05);
      }
      return 500; // Flat base commission in INR
    case "tiffin":
      // Flat ₹150 lead referral commission per meal subscription signup
      return 150;
    case "broadband":
      // Flat ₹300 commission per high-speed internet installation lead
      return 300;
    default:
      return 100;
  }
}

export function useMarketplaceLeads() {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  /**
   * Tracks a new lead generator and calculates B2B commission.
   */
  const trackMarketplaceLead = useCallback(async (
    leadData: Omit<MarketplaceLead, "id" | "commissionAmount" | "status" | "createdAt">
  ): Promise<string> => {
    setLoading(true);
    setError(null);
    try {
      const commissionAmount = calculateB2BCommission(leadData.partnerType, leadData.payloadDetails);
      const colRef = collection(db, "marketplace_leads");
      
      const record: Omit<MarketplaceLead, "id"> = {
        ...leadData,
        commissionAmount,
        status: "pending",
        createdAt: new Date().toISOString()
      };

      const docRef = await addDoc(colRef, record);
      await updateDoc(docRef, { id: docRef.id });
      
      setLoading(false);
      return docRef.id;
    } catch (err: any) {
      const errMsg = err?.message || "Failed to record marketplace lead referer.";
      setError(errMsg);
      setLoading(false);
      try {
        handleFirestoreError(err, OperationType.CREATE, "marketplace_leads");
      } catch (e) {}
      throw err;
    }
  }, []);

  /**
   * Retrieves marketplace leads generated by a specific user.
   */
  const getUserLeads = useCallback(async (userId: string): Promise<MarketplaceLead[]> => {
    setLoading(true);
    setError(null);
    try {
      const colRef = collection(db, "marketplace_leads");
      const q = query(colRef, where("userId", "==", userId), orderBy("createdAt", "desc"));
      const snapshot = await getDocs(q);
      
      const list: MarketplaceLead[] = [];
      snapshot.forEach((docSnap) => {
        list.push({ ...docSnap.data(), id: docSnap.id } as MarketplaceLead);
      });
      
      setLoading(false);
      return list;
    } catch (err: any) {
      setError(err?.message || "Failed to fetch user leads.");
      setLoading(false);
      return [];
    }
  }, []);

  return {
    trackMarketplaceLead,
    getUserLeads,
    loading,
    error
  };
}
